# Generated by Django 4.2.6 on 2023-10-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_product_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='reporter',
        ),
        migrations.AddField(
            model_name='category',
            name='product',
            field=models.ManyToManyField(to='page.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(max_length=2000),
        ),
    ]
