# Generated by Django 4.2.6 on 2023-10-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_remove_product_reporter_category_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='button',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
