# Generated by Django 4.2.6 on 2023-10-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_product_button'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='button',
            new_name='button_text',
        ),
        migrations.RemoveField(
            model_name='category',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, to='page.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
