# Generated by Django 4.2.6 on 2023-10-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_team_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('img', models.ImageField(upload_to='uploads/')),
                ('snippet', models.TextField()),
                ('body', models.TextField()),
            ],
        ),
    ]
