# Generated by Django 4.2.6 on 2023-10-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
