# Generated by Django 4.2.6 on 2023-10-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_blog_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
