# Generated by Django 4.2.6 on 2023-10-21 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='snippet',
        ),
    ]
