# Generated by Django 4.2.6 on 2023-11-03 15:54

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0012_remove_blog_snippet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('img', models.ImageField(upload_to='uploads/')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('year', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
